name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date +%Y%m%d)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-{{ env.cache_id }}
          path: .cache
      - name: Install pngquant system package
        run: sudo apt-get update && sudo apt-get install -y pngquant
      - run: pip install "mkdocs-materialx[imaging]" pymdown-extensions pymdown-multimd-table mkdocstrings mkdocstrings-python mkdocs-click mkdocs-rss-plugin mkdocs-table-reader-plugin mkdocs-glightbox markdown-exec mkdocs-section-index mkdocs-open-in-new-tab mkdocs-schema-reader mkdocs-caption mkdocs-minify-plugin
      - run: mkdocs build --clean
      - run: sed -i 's|/assets/local_icons/|/Afridyne-Systems/assets/local_icons/|g' site/search/search_index.json site/assets/javascripts/*.js 2>/dev/null || true
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

